version: '3.0'
services:
  api:
    image: api:1.0.1
    ports:
      - 8888:8888
    hostname: 'api'
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.api == true]
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network


networks:
  my_network:
    external: true